### ISSUE TITLE
use `from pysixdesk import *` to actually import relevant classes

### ISSUE THREAD

**Issue by amereghe** [SixTrack/pysixdesk#8]
It would be great to give the possibility to users to import very quickly all the classes and vars in the pysixdesk modules. I think that this can be accomplished with the `__init__.py` module in the `pysixdesk` folder

**Comment by luxiaohan** [comment]
I have imported all the modules within __init__.py in the pysixdesk folder.

**Comment by amereghe** [comment]
cross-checked with @luxiaohan that code is in - closing issue
